version: "0.2"
files:
  - "*.md"
dictionaryDefinitions: []
dictionaries: []
words:
  - AMWA
  - arping
  - Bootable
  - CBNT
  - Clonezilla
  - comptia
  - DCIM
  - DECSAR
  - dhclient
  - dhcpcd
  - EXFO
  - flushdns
  - IPAM
  - Iperf
  - kenlon
  - kozk
  - Kurose
  - Liebman
  - Meinberg
  - Memtest
  - mydnsserver
  - netsh
  - netshoot
  - networkctl
  - Nmap
  - NMOS
  - noall
  - nocmd
  - nslookup
  - ntpq
  - OTDR
  - OTDRs
  - pandoc
  - pathping
  - pcap
  - pinout
  - reflectometer
  - reflectometers
  - Rescatux
  - rrtype
  - sdpoker
  - SirusXM
  - SMPTE
  - tcpdump
  - traceroute
  - tracert
  - traefik
  - Ventoy
  - Wireshark
ignoreWords: []
import: []
