name: Build Slides

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  convert_via_pandoc:
    name: Convert via pandoc
    needs: pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - uses: r-lib/actions/setup-pandoc@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          pandoc-version: 3.1.11
      - run: |
          pandoc --citeproc \
            --filter=node_modules/.bin/mermaid-filter \
            --from=markdown+yaml_metadata_block+emoji \
            --slide-level=3 \
            ./media-net-fundamentals.md \
            -o ./media-net-fundamentals.pptx
      - run: |
          pandoc --citeproc \
            --filter=node_modules/.bin/mermaid-filter \
            --from=markdown+yaml_metadata_block+emoji \
            --slide-level=3 \
            -t revealjs \
            --standalone \
            --embed-resources \
            -V revealjs-url=https://unpkg.com/reveal.js/ \
            ./media-net-fundamentals.md \
            -o ./media-net-fundamentals.pptx
      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@3aae7a13f0a57f433e694fddb74a1a05abeb9b99 # v0.0.15
        with:
          duration: 30m
          authorized-users: michaelliebman
